### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by nighthauk** [rudders/homebridge-wemo#36]
Just general feedback. Incredibly annoying y'all feel like you have to have cut a new release every few days. Not necessary. And your node requirements aren't necessary either.

**Comment by esetnik** [comment]
>  Incredibly annoying y'all feel like you have to have cut a new release every few days.

You aren't forced to install any updates. Why do you care if the maintainers cut a new release every few days?

> And your node requirements aren't necessary either.

 I agree re. node requirements they should be set to the lowest possible supported version.

**Comment by nighthauk** [comment]
Honestly I think it's the node requirement that fuels the annoyance for me personally. No disrespect to the maintainers, I appreciate the work. Just giving some feedback in hopes that releases become a little more transparent.

**Comment by bwp91** [comment]
On the readme page, it states

> Whilst it is recommended to use Node v16, the plugin supports v12 and v14 as per the Homebridge guidelines.

And on the changelog for releases it says

> Bump node recommended versions to v14.18.1 or v16.13.0

**Recommended** being the key word. I believe keeping these recommended versions of node up-to-date is a great way to alert/remind users that a new version of node is available to install. I believe keeping node up-to-date is just as important as keeping homebridge and plugins up-to-date.

But currently, the plugin will function on all versions of v12, v14 and v16. You *don't have* to keep node up to date.

In April 2022, the plugin will be dropping support for node 12 so I can start using some of the newer syntax introduced in node 14.

**Comment by bwp91** [comment]
And with regards to releases, I normally release a new version as and when I have made a fix for an issue or some improvement. I won't release a new version of the plugin say *just* because a new version of node is available.

**Comment by nighthauk** [comment]
All makes sense, appreciate the work on this of course.

**Comment by esetnik** [comment]
> Recommended being the key word. I believe keeping these recommended versions of node up-to-date is a great way to alert/remind users that a new version of node is available to install. I believe keeping node up-to-date is just as important as keeping homebridge and plugins up-to-date.

@bwp91 I think the issue for me and other users is the scary warning shown when the plugin runs on a different version of node. On my platform there is no availability of v16.13 and so on every launch of homebridge I get a scary warning saying that the plugin is incompatible (when it's not actually incompatible) and there's nothing I can do about it since I cannot upgrade node. According to the `package.json` documentation https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines for engines:
> You can specify the version of node that your stuff works on:

This plugin is not using the engines field in the manner in which it was intended. I don't really see any reason for this plugin to be opinionated about what version of node it's users are running as long as the plugin is fully functional on those versions. If there is an incompatible version of node then by all means it should be excluded, but otherwise it's just leading to unnecessary warning noise in my opinion.

Thank you so much for your hard work and the great plugin.

**Comment by nighthauk** [comment]
Agree with @esetnik entirely. This is the primary reason I opened, just didn't state it as eloquently as I could have. For that I apologize. 

When the UI tells me I have updates so frequently, yet the messaging says I may have issues unless I also upgrade node, it gives the perception that my setup is always outdated when it's not. So I upgrade node and then this package only to have another update notice a few days later.

**Comment by donavanbecker** [comment]
@nighthauk and @esetnik do you expect him to test on every node version? If he is putting the newest node version, he is probably testing and running on that specific version. Just something to think about.

**Comment by esetnik** [comment]
> @nighthauk and @esetnik do you expect him to test on every node version? If he is putting the newest node version, he is probably testing and running on that specific version. Just something to think about.

No, I definitely don't expect that. I have no expectations from the author. But I do think that since this plugin is not doing anything which would cause it to likely be incompatible with a specific node version then it should be up to the community to report issues (if there are any) on specific node versions. The engine field is supposed to be used to warn of known incompatibilities and to my knowledge, there are none in 14 and 16.
